import { useState, useEffect } from 'react'
import styled from 'styled-components'
import { hybridAPI, analystAPI } from '../services/api'
import { 
  Chart as ChartJS, 
  ArcElement, 
  Tooltip, 
  Legend, 
  CategoryScale, 
  LinearScale, 
  BarElement, 
  Title 
} from 'chart.js';
import { Pie } from 'react-chartjs-2';

import { 
  FiActivity, FiAlertTriangle, FiCheckCircle, FiClock, 
  FiRefreshCw, FiTrendingUp, FiMapPin
} from 'react-icons/fi'

ChartJS.register(ArcElement, Tooltip, Legend, CategoryScale, LinearScale, BarElement, Title);

const DashboardContainer = styled.div`display: flex; flex-direction: column; gap: 2rem;`
const TopBar = styled.div`display: flex; justify-content: space-between; align-items: center;`
const PageTitle = styled.div`
  h2 { font-size: 1.75rem; color: var(--text-primary); font-weight: 600; }
  p { color: var(--text-secondary); font-size: 0.95rem; }
`
const RefreshButton = styled.button`
  display: flex; align-items: center; gap: 0.5rem; padding: 0.75rem 1.5rem;
  background: var(--bg-tertiary); border: 1px solid var(--border-color); color: var(--text-primary);
  border-radius: var(--radius-md); cursor: pointer;
  &:hover { background: var(--primary); box-shadow: var(--shadow-glow); }
`
const StatsGrid = styled.div`display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1.5rem;`
const StatCard = styled.div`
  background: var(--bg-card); border: 1px solid var(--border-color); border-radius: var(--radius-lg); padding: 1.5rem;
  position: relative; overflow: hidden;
  &::before { content: ''; position: absolute; top: 0; left: 0; right: 0; height: 3px; background: ${props => props.$color || 'var(--primary)'}; }
`
const ChartCard = styled.div`
  background: var(--bg-card); border: 1px solid var(--border-color); border-radius: var(--radius-lg); padding: 1.5rem;
  h3 { font-size: 1.125rem; color: var(--text-primary); margin-bottom: 1.5rem; display: flex; align-items: center; gap: 0.5rem; }
`

const Dashboard = () => {
  const [analytics, setAnalytics] = useState({
    totalTransactions: 0, lowRisk: 0, mediumRisk: 0, highRisk: 0,
    approvedCount: 0, holdCount: 0, blockedCount: 0, autoGeneratedCount: 0
  })
  const [recentTransactions, setRecentTransactions] = useState([]);

  const fetchData = async () => {
    try {
      const response = await hybridAPI.getAnalytics();
      setAnalytics(response.data);
      const txResponse = await analystAPI.getTransactions({ page: 0, size: 50 });
      setRecentTransactions(txResponse.data.transactions || []);
    } catch (error) { console.error('Error:', error); }
  }

  useEffect(() => {
    fetchData();
    const interval = setInterval(fetchData, 3000);
    return () => clearInterval(interval);
  }, [])

  const statusPieData = {
    labels: ['Approved', 'On Hold', 'Blocked'],
    datasets: [{
      data: [analytics.approvedCount, analytics.holdCount, analytics.blockedCount],
      backgroundColor: ['#4caf50', '#ff9800', '#f44336'],
      borderColor: '#1e2235',
      borderWidth: 2,
    }]
  };

  return (
    <DashboardContainer>
      <TopBar>
        <PageTitle>
          <h2>Real-Time Transaction Monitoring</h2>
          <p>Global Fraud Surveillance Active (ML + Rule Engine)</p>
        </PageTitle>
        <RefreshButton onClick={fetchData}><FiRefreshCw /> Sync Data</RefreshButton>
      </TopBar>

      <StatsGrid>
        <StatCard $color="#4c6ef5">
          <div style={{fontSize: '0.75rem', color: '#888'}}>TOTAL TRANSACTIONS</div>
          <div style={{fontSize: '1.8rem', fontWeight: '700'}}>{analytics.totalTransactions}</div>
        </StatCard>
        <StatCard $color="#4caf50">
          <div style={{fontSize: '0.75rem', color: '#888'}}>SAFE (LOW)</div>
          <div style={{fontSize: '1.8rem', fontWeight: '700'}}>{analytics.lowRisk}</div>
        </StatCard>
        <StatCard $color="#ff9800">
          <div style={{fontSize: '0.75rem', color: '#888'}}>REVIEW (MED)</div>
          <div style={{fontSize: '1.8rem', fontWeight: '700'}}>{analytics.mediumRisk}</div>
        </StatCard>
        <StatCard $color="#f44336">
          <div style={{fontSize: '0.75rem', color: '#888'}}>FRAUD (HIGH)</div>
          <div style={{fontSize: '1.8rem', fontWeight: '700'}}>{analytics.highRisk}</div>
        </StatCard>
      </StatsGrid>

      <div style={{ display: 'grid', gridTemplateColumns: '1.6fr 1fr', gap: '1.5rem' }}>
        {/* LIGHTWEIGHT SVG MAP HACK */}
        <ChartCard>
          <h3><FiMapPin color="#f44336" /> Live Geographical Fraud Heatmap</h3>
          <div style={{ 
            height: '350px', 
            background: `url('https://upload.wikimedia.org/wikipedia/commons/8/80/World_map_-_low_resolution.svg')`,
            backgroundSize: 'contain', backgroundRepeat: 'no-repeat', backgroundPosition: 'center',
            backgroundColor: '#151724', borderRadius: '8px', position: 'relative', border: '1px solid rgba(255,255,255,0.05)'
          }}>
            {recentTransactions.filter(tx => tx.riskLevel !== 'LOW').slice(0, 10).map((tx, idx) => {
              const posMap = {
                "Indore": { top: '58%', left: '72%' }, "Mumbai": { top: '62%', left: '71%' },
                "Dubai": { top: '55%', left: '62%' }, "New York": { top: '42%', left: '26%' },
                "London": { top: '35%', left: '48%' }, "Singapore": { top: '65%', left: '80%' }
              };
              const pos = posMap[tx.location] || { top: '50%', left: '50%' };
              const color = tx.riskLevel === 'HIGH' ? '#f44336' : '#ff9800';
              return (
                <div key={idx} style={{ position: 'absolute', top: pos.top, left: pos.left, transform: 'translate(-50%, -50%)' }}>
                  <div style={{ width: '10px', height: '10px', backgroundColor: color, borderRadius: '50%', border: '2px solid white', boxShadow: `0 0 10px ${color}` }} />
                  <div style={{ position: 'absolute', top: '-20px', left: '10px', color: '#fff', fontSize: '10px', whiteSpace: 'nowrap', background: 'rgba(0,0,0,0.7)', padding: '2px 5px', borderRadius: '4px' }}>
                    {tx.location} (₹{tx.amount.toLocaleString()})
                  </div>
                </div>
              );
            })}
          </div>
        </ChartCard>

        <ChartCard>
          <h3><FiActivity /> Transaction Status</h3>
          <div style={{ height: '300px' }}>
            <Pie data={statusPieData} options={{ maintainAspectRatio: false, plugins: { legend: { position: 'bottom', labels: { color: '#fff' } } } }} />
          </div>
        </ChartCard>
      </div>

      <ChartCard>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <h3>Auto-Generation Engine</h3>
            <p style={{ color: '#888', fontSize: '0.85rem' }}>Simulating real-world traffic patterns</p>
          </div>
          <div style={{ textAlign: 'right' }}>
            <span style={{ fontSize: '1.5rem', fontWeight: '700', color: 'var(--primary)' }}>{analytics.autoGeneratedCount}</span>
            <div style={{ color: '#4caf50', fontSize: '0.75rem' }}>● SYSTEM LIVE</div>
          </div>
        </div>
      </ChartCard>
    </DashboardContainer>
  )
}

export default Dashboard









































// import { useState, useEffect } from 'react'
// import styled from 'styled-components'
// import { hybridAPI } from '../services/api'
// import { 
//   Chart as ChartJS, 
//   ArcElement, 
//   Tooltip, 
//   Legend, 
//   CategoryScale, 
//   LinearScale, 
//   BarElement, 
//   Title 
// } from 'chart.js';
// import { Pie, Bar } from 'react-chartjs-2';

// import { 
//   FiActivity, FiAlertTriangle, FiCheckCircle, FiClock, 
//   FiRefreshCw, FiTrendingUp 
// } from 'react-icons/fi'

// // Register ChartJS components
// ChartJS.register(
//   ArcElement, Tooltip, Legend, 
//   CategoryScale, LinearScale, BarElement, Title
// );

// const DashboardContainer = styled.div`
//   display: flex;
//   flex-direction: column;
//   gap: 2rem;
// `

// const TopBar = styled.div`
//   display: flex;
//   justify-content: space-between;
//   align-items: center;
  
//   @media (max-width: 768px) {
//     flex-direction: column;
//     gap: 1rem;
//     align-items: flex-start;
//   }
// `

// const PageTitle = styled.div`
//   h2 {
//     font-size: 1.75rem;
//     color: var(--text-primary);
//     font-weight: 600;
//     margin-bottom: 0.5rem;
//   }
  
//   p {
//     color: var(--text-secondary);
//     font-size: 0.95rem;
//   }
// `

// const RefreshButton = styled.button`
//   display: flex;
//   align-items: center;
//   gap: 0.5rem;
//   padding: 0.75rem 1.5rem;
//   background: var(--bg-tertiary);
//   border: 1px solid var(--border-color);
//   color: var(--text-primary);
//   border-radius: var(--radius-md);
//   cursor: pointer;
//   font-weight: 500;
//   transition: var(--transition);
  
//   svg {
//     font-size: 1.25rem;
//   }
  
//   &:hover {
//     background: var(--primary);
//     border-color: var(--primary);
//     box-shadow: var(--shadow-glow);
//   }
  
//   &:active svg {
//     animation: spin 0.5s ease;
//   }
  
//   @keyframes spin {
//     from { transform: rotate(0deg); }
//     to { transform: rotate(360deg); }
//   }
// `

// const StatsGrid = styled.div`
//   display: grid;
//   grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
//   gap: 1.5rem;
// `

// const StatCard = styled.div`
//   background: var(--bg-card);
//   border: 1px solid var(--border-color);
//   border-radius: var(--radius-lg);
//   padding: 1.5rem;
//   transition: var(--transition);
//   position: relative;
//   overflow: hidden;
  
//   &::before {
//     content: '';
//     position: absolute;
//     top: 0;
//     left: 0;
//     right: 0;
//     height: 3px;
//     background: ${props => props.$color || 'var(--primary)'};
//   }
  
//   &:hover {
//     transform: translateY(-4px);
//     box-shadow: var(--shadow-lg);
//     border-color: ${props => props.$color || 'var(--primary)'};
//   }
// `

// const StatHeader = styled.div`
//   display: flex;
//   justify-content: space-between;
//   align-items: flex-start;
//   margin-bottom: 1rem;
// `

// const StatIcon = styled.div`
//   width: 48px;
//   height: 48px;
//   border-radius: var(--radius-md);
//   background: ${props => props.$color ? `${props.$color}20` : 'rgba(76, 110, 245, 0.2)'};
//   display: flex;
//   align-items: center;
//   justify-content: center;
  
//   svg {
//     font-size: 1.5rem;
//     color: ${props => props.$color || 'var(--primary)'};
//   }
// `

// const StatLabel = styled.div`
//   font-size: 0.875rem;
//   color: var(--text-secondary);
//   font-weight: 500;
//   text-transform: uppercase;
//   letter-spacing: 0.5px;
// `

// const StatValue = styled.div`
//   font-size: 2rem;
//   font-weight: 700;
//   color: var(--text-primary);
//   margin-bottom: 0.5rem;
// `

// const StatChange = styled.div`
//   font-size: 0.875rem;
//   color: ${props => props.$positive ? 'var(--success)' : 'var(--danger)'};
//   display: flex;
//   align-items: center;
//   gap: 0.25rem;
  
//   svg {
//     font-size: 1rem;
//   }
// `

// const ChartCard = styled.div`
//   background: var(--bg-card);
//   border: 1px solid var(--border-color);
//   border-radius: var(--radius-lg);
//   padding: 1.5rem;
//   margin-top: 2rem;
  
//   h3 {
//     font-size: 1.125rem;
//     color: var(--text-primary);
//     font-weight: 600;
//     margin-bottom: 1.5rem;
//     display: flex;
//     align-items: center;
//     gap: 0.5rem;
    
//     svg {
//       color: var(--primary);
//     }
//   }
// `

// const Dashboard = () => {
//   const [analytics, setAnalytics] = useState({
//     totalTransactions: 0,
//     lowRisk: 0,
//     mediumRisk: 0,
//     highRisk: 0,
//     approvedCount: 0,
//     holdCount: 0,
//     blockedCount: 0,
//     autoGeneratedCount: 0
//   })

//   const fetchAnalytics = async () => {
//     try {
//       const response = await hybridAPI.getAnalytics()
//       setAnalytics(response.data)
//     } catch (error) {
//       console.error('Error fetching analytics:', error)
//     }
//   }

//   useEffect(() => {
//     fetchAnalytics()
//     const interval = setInterval(fetchAnalytics, 2000)
//     return () => clearInterval(interval)
//   }, [])

//   // Dynamic Pie Chart Data
//   const pieData = {
//     labels: ['Safe (Low Risk)', 'Review (Medium)', 'Fraud (High Risk)'],
//     datasets: [{
//       data: [analytics.lowRisk, analytics.mediumRisk, analytics.highRisk],
//       backgroundColor: ['#4caf50', '#ff9800', '#f44336'],
//       hoverOffset: 4
//     }]
//   };

//   // Dynamic Bar Chart Data
//   const barData = {
//     labels: ['Approved', 'On Hold', 'Blocked'],
//     datasets: [{
//       label: 'Transaction Count',
//       data: [analytics.approvedCount, analytics.holdCount, analytics.blockedCount],
//       backgroundColor: ['#4caf50', '#ff9800', '#f44336'],
//       borderRadius: 8
//     }]
//   };

//   return (
//     <DashboardContainer>
//       <TopBar>
//         <PageTitle>
//           <h2>Real-Time Transaction Monitoring</h2>
//           <p>Monitor fraud detection in real-time with ML + Rule-based analysis</p>
//         </PageTitle>
//         <RefreshButton onClick={fetchAnalytics}>
//           <FiRefreshCw />
//           Refresh
//         </RefreshButton>
//       </TopBar>

//       <StatsGrid>
//         <StatCard $color="var(--primary)">
//           <StatHeader>
//             <StatLabel>Total Transactions</StatLabel>
//             <StatIcon $color="var(--primary)">
//               <FiActivity />
//             </StatIcon>
//           </StatHeader>
//           <StatValue>{analytics.totalTransactions}</StatValue>
//           <StatChange $positive>
//             <FiTrendingUp />
//             Live monitoring active
//           </StatChange>
//         </StatCard>

//         <StatCard $color="var(--success)">
//           <StatHeader>
//             <StatLabel>Low Risk</StatLabel>
//             <StatIcon $color="var(--success)">
//               <FiCheckCircle />
//             </StatIcon>
//           </StatHeader>
//           <StatValue>{analytics.lowRisk}</StatValue>
//           <StatChange $positive>
//             Approved: {analytics.approvedCount}
//           </StatChange>
//         </StatCard>

//         <StatCard $color="var(--warning)">
//           <StatHeader>
//             <StatLabel>Medium Risk</StatLabel>
//             <StatIcon $color="var(--warning)">
//               <FiClock />
//             </StatIcon>
//           </StatHeader>
//           <StatValue>{analytics.mediumRisk}</StatValue>
//           <StatChange>
//             On Hold: {analytics.holdCount}
//           </StatChange>
//         </StatCard>

//         <StatCard $color="var(--danger)">
//           <StatHeader>
//             <StatLabel>High Risk</StatLabel>
//             <StatIcon $color="var(--danger)">
//               <FiAlertTriangle />
//             </StatIcon>
//           </StatHeader>
//           <StatValue>{analytics.highRisk}</StatValue>
//           <StatChange $positive={false}>
//             Blocked: {analytics.blockedCount}
//           </StatChange>
//         </StatCard>
//       </StatsGrid>

//       {/* CHARTS SECTION */}
//       <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(400px, 1fr))', gap: '1.5rem', marginTop: '1rem' }}>
//           <ChartCard>
//               <h3><FiActivity /> Risk Distribution</h3>
//               <div style={{ height: '300px', display: 'flex', justifyContent: 'center' }}>
//                   <Pie data={pieData} options={{ maintainAspectRatio: false }} />
//               </div>
//           </ChartCard>

//           <ChartCard>
//               <h3><FiActivity /> Transaction Status</h3>
//               <div style={{ height: '300px' }}>
//                   <Bar data={barData} options={{ maintainAspectRatio: false, scales: { y: { beginAtZero: true } } }} />
//               </div>
//           </ChartCard>
//       </div>

//       <ChartCard>
//         <h3>
//           <FiActivity />
//           Auto-Generation Status
//         </h3>
//         <p style={{ color: 'var(--text-secondary)', marginBottom: '1rem' }}>
//           System automatically generates 1 transaction every 5 seconds
//         </p>
//         <div style={{ 
//           padding: '1rem', 
//           background: 'var(--bg-tertiary)', 
//           borderRadius: 'var(--radius-md)',
//           display: 'flex',
//           justifyContent: 'space-between',
//           alignSize: 'center'
//         }}>
//           <span style={{ color: 'var(--text-secondary)' }}>
//             Auto-generated transactions:
//           </span>
//           <span style={{ 
//             fontSize: '1.5rem', 
//             fontWeight: '700', 
//             color: 'var(--primary-light)' 
//           }}>
//             {analytics.autoGeneratedCount}
//           </span>
//         </div>
//         <div style={{ 
//           marginTop: '1rem', 
//           display: 'flex', 
//           alignItems: 'center', 
//           gap: '0.5rem',
//           color: 'var(--success)'
//         }}>
//           <div style={{
//             width: '8px',
//             height: '8px',
//             borderRadius: '50%',
//             background: 'var(--success)',
//             animation: 'pulse 2s ease-in-out infinite'
//           }} />
//           System Running
//         </div>
//       </ChartCard>
//     </DashboardContainer>
//   )
// }

// export default Dashboard